// app/layout.js/
import { Inter } from "next/font/google";
import "./globals.css";
import { ImageProvider } from './context/ImageContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ImageProvider> {/* Wrap your application with the provider */}
          {children} 
        </ImageProvider>
      </body>
    </html>
  );
}
